accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('contact_us/', views.ContactView.as_view(), name='contact'),
    path(
        'online_booking/',
        views.OnlineBookingView.as_view(),
        name='online_booking'
    ),
    path(
        'create_profile/',
        views.CreateProfile.as_view(),
        name='create_profile'
    ),
    path(
        'edit_profile/<str:user>/',
        views.EditProfile.as_view(),
        name='edit_profile'
    ),
    path(
        'manage_booking/',
        views.ManageBooking.as_view(),
        name='manage_booking'
    ),
    path(
        'edit_booking/<str:booking_id>/',
        views.EditBooking.as_view(),
        name='edit_booking'
    ),
    path(
        'delete_booking/<str:booking_id>/',
        views.DeleteBooking.as_view(),
        name='delete_booking'
    ),
]

pawfectionparlour/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'), name='home'),
    path('accounts/', include('allauth.urls')),
]

accounts/models.py
import uuid
from django.db import models

# Import Django authentication user system
from django.contrib.auth.models import User

# Create your models here.
STATUS = ((0, "Booking Requested"), (1, "Booking Accepted"))


class Booking(models.Model):
    booking_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_bookings"
    )
    booking_date = models.DateField(auto_now=False)
    booking_time = models.TimeField(auto_now=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-booking_date"]


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    dog_name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=11)

    def __str__(self):
        return str(self.user)

accounts/forms.py
from django.forms import CharField, TextInput
from .models import Booking, UserProfile
from django import forms


class UpdateBookingDetails(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ("booking_date", "booking_time")


class EditProfileForm(forms.ModelForm):

    phone_number = CharField(widget=TextInput(attrs={"type": "number"}))

    class Meta:
        model = UserProfile
        fields = ("first_name", "last_name", "dog_name", "phone_number")       

accounts/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect

# Import Django generic libary
from django.views import generic, View
from django.views.generic import TemplateView, DeleteView
from django.urls import reverse_lazy

# Import Booking model from models
from .models import Booking, UserProfile
from .forms import UpdateBookingDetails, EditProfileForm

# Create your views here.


class HomeView(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "index.html",
        )


class ServicesView(TemplateView):
    template_name = "services.html"

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "services.html",
        )


class ContactView(TemplateView):
    template_name = "contact.html"

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "contact.html",
        )


class ManageBooking(generic.ListView):
    model = Booking
    queryset = Booking.objects.all()
    template_name = "manage_booking.html"
    paginate_by = 6
    extra_context = {"manage_booking_active": "custom-red"}


def get_queryset(self):
    return Booking.objects.filter(user_id=self.request.user)


class OnlineBookingView(View):
    template_name = "online_booking.html"

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "online_booking.html",
            {
                "online_booking_active": "custom-red",
            },
        )

    def post(self, request):
        date = request.POST.get("date")
        time = request.POST.get("time")

        online_booking = Booking.objects.create(
            booking_date=date,
            booking_time=time,
            user=request.user,
        )

        online_booking.save()

        return redirect(reverse("manage_booking"))


class EditBooking(View):
    model = Booking
    template_name = "edit_booking.html"
    context_object_name = "edit_booking"

    def get(self, request, booking_id, *args, **kwargs):
        booking = get_object_or_404(Booking, pk=booking_id)

        return render(
            request,
            "edit_booking.html",
            {
                "booking": booking,
                "updated": False,
                "Update_BookingDetails": UpdateBookingDetails(instance=booking),
            },
        )

    def post(self, request, booking_id, *args, **kwargs):
        booking = get_object_or_404(Booking, pk=booking_id)

        booking_details_form = UpdateBookingDetails(request.POST, instance=booking)

        if booking_details_form.is_valid():
            booking.status = 0
            booking_updates = booking_details_form.save()
        else:
            booking_details_form = UpdateBookingDetails(instance=booking)

        return render(
            request,
            "edit_booking.html",
            {
                "booking": booking,
                "updated": True,
                "Update_BookingDetails": booking_details_form,
            },
        )


class DeleteBooking(DeleteView):
    model = Booking
    pk_url_kwarg = "booking_id"
    success_url = reverse_lazy("manage_booking")
    template_name = "delete_booking.html"


class CreateProfile(View):
    template_name = "create_profile.html"

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "create_profile.html",
        )

    def post(self, request):
        f_name = request.POST.get("f_name")
        l_name = request.POST.get("l_name")
        dog_name = request.POST.get("dog_name")
        tele = request.POST.get("phone_number")

        CreateUserProfile = UserProfile.objects.create(
            first_name=f_name,
            last_name=l_name,
            phone_number=tele,
            user=request.user,
        )

        CreateUserProfile.save()

        return redirect(reverse("home"))


class EditProfile(View):
    model = UserProfile
    template_name = "edit_profile.html"
    context_object_name = "edit_profile"

    def get(self, request, user, *args, **kwargs):
        profile = UserProfile.objects.filter(user=user).first()
        if profile is None:
            return redirect(reverse("create_profile"))

        return render(
            request,
            "edit_profile.html",
            {
                "profile": profile,
                "updated": False,
                "Edit_ProfileForm": EditProfileForm,
                "edit_profile_active": "custom-red",
            },
        )

    def post(self, request, user, *args, **kwargs):
        profile = UserProfile.objects.get(user=user)

        edit_profile_form = EditProfileForm(request.POST, instance=profile)

        if edit_profile_form.is_valid():
            profile_updates = edit_profile_form.save()
        else:
            edit_profile_form = EditProfileForm(instance=profile)

        return render(
            request,
            "edit_profile.html",
            {
                "profile": profile,
                "updated": True,
                "Edit_ProfileForm": edit_profile_form,
            },
        )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <title>Pawfection Parlour</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body class="d-flex flex-column h-100">
    
    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg bg-success">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="{% url 'home' %}">Pawfection Parlour
            </a>

            <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse text-white" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item px-2">
                        <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                    </li>

                    <li class="nav-item px-2">
                        <a class="nav-link text-white"href="{% url 'services' %}">Services</a>
                    </li>

                    <li class="nav-item px-2">
                        <a class="nav-link text-white"href="{% url 'contact' %}">Contact</a>
                    </li>

                    <li class="nav-item px-2">
                        <a class="nav-link text-white"href="{% url 'online_booking' %}">Book Now</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item px-2">
                        <a class="nav-link text-white {{ edit_profile_active }}"
                            href="{% url 'edit_profile' request.user.id %}">Edit Profile</a>
                    </li>

                    <li class="nav-item px-2">
                        <a class="nav-link text-white {{ manage_booking_active }}" href="{% url 'manage_booking' %}">Manage
                            Bookings</a>
                    </li>

                    <li class="nav-item px-2">
                        <a class="nav-link text-white" href="{% url 'account_logout' %}">Logout</a>
                    </li>

                    {% else %}

                    <li class="nav-item px-2">
                        <a class="nav-link text-white" href="{% url 'account_signup' %}">Register</a>
                    </li>

                    <li class="nav-item px-2">
                        <a class="nav-link text-white" href="{% url 'account_login' %}">Login</a>
                    </li>

                    {% endif %}

                
                </ul>
            </div>
        </div>
    </nav>


        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

    <!-- Footer -->
    <footer class="bg-success text-center text-white mt-auto" id="footer">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #3b5998;"
              href="https://www.facebook.com/"
              role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #55acee;"
              href="https://twitter.com/"
              role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #dd4b39;"
              href="https://www.google.com/"
              role="button"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #ac2bac;"
              href="https://www.instagram.com/"
              role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #0082ca;"
              href="https://gb.linkedin.com/"
              role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2022 Copyright:
          <a class="text-white" href="">Pawfection Parlour</a>
        </div>
        <!-- Copyright -->
      </footer>
</body>

</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}

<div class="container ">
    <div class="row ">
        <div class="col-md-5 col-12 mx-auto py-5">
            <div class="contact_icons my-3">
                <i class="fas fa-phone font-weight-normal"> +353 83 077 8985</i>
            </div>

            <div class="contact_icons my-3">
                <i class="fas fa-envelope"> pawfectionparlour24@gmail.com</i>
            </div>

            <div class="contact_icons my-3">
                <i class="fas fa-clock"> Mon-Fri 08:00 - 17:00 </i>
            </div>

            <div class="contact_icons my-3">
                <i class="fas fa-map-marker-alt"> Bohernabreena Rd, Bohernabreena, Tallaght, D24 A218</i>
            </div>
        </div>

        <div class="col-md-5 col-12 mx-auto py-5">
            <form method="POST" action="https://formdump.codeinstitute.net/">
                <label for="full_name" class="form-label">Full Name</label>
                <input type="text" class="form-control text_input" name="full_name" id="full_name"
                    value="{{ user.userprofile.first_name }} {{ user.userprofile.last_name }}" required>

                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control text_input" name="email_address" id="email"
                    value="{{ user.email }}" required>

                <label for="message">Your message</label>
                <textarea class="form-control" name="message" id="message" rows="3" required></textarea>

                <button type="submit" class="btn bg-success text-white mx-auto d-block my-3">
                    Submit Message
                </button>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-12 w-75 mx-auto">
            <iframe class="w-100" height="600"
                src="https://maps.google.com/maps?q=pawfection%20parlour&t=&z=13&ie=UTF8&iwloc=&output=embed">
            </iframe>
        </div>
    </div>
</div>

{% endblock %}

templates/create_profile.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
<div class="w-50 mx-auto py-5">
    <form class="row g-3" method="POST">
        {% csrf_token %}

        <div class="col-12">
            <label for="f_name">First Name</label>
            <input type="text" class="form-control" id="f_name" name="f_name">
        </div>

        <div class="col-12">
            <label for="l_name">Last Name</label>
            <input type="text" class="form-control" id="l_name" name="l_name">
        </div>

        <div class="col-12">
            <label for="dog_name">Dog Name</label>
            <input type="text" class="form-control" id="dog_name" name="dog_name">
        </div>

        <div class="col-12 mx-auto">
            <label for="phone_number">Telephone Number</label>
            <input type="number" class="form-control" id="phone_number" name="phone_number" minlength="11" maxlength="11">
        </div>

        <div class="col-12 text-center">
            <a href="/"> <button type="submit" class="btn bg-success text-white">Create Profile</button>
            </a>
        </div>
    </form>
</div>
{% else %}

Please login to edit your profile

{% endif %}

{% endblock %}

templates/delete_booking.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
<div class="w-75 mx-auto py-5">
    <form action="." method="POST">
        {% csrf_token %}

        <h3>Do you want to cancel the booking "{{ booking.booking_id }}"?</h3>

        <button class="btn bg-success text-white" type="submit">Yes</button>

        <a class="btn bg-success text-white" href="{% url 'manage_booking' %}">
            Cancel
        </a>
    </form>
</div>
{% else %}

Please login to cancel your booking

{% endif %}

{% endblock %}

templates/edit_booking.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container text-center custom-red mt-5">
    <div class="row my-3">
        <div class="col-12">
            <h2 class="text-decoration-underline">Booking Details</h2>
        </div>
    </div>

    <div class="row my-3">
        <div class="col-6">
            <h5>Booking Status:</h5>
        </div>
        <div class="col-6">
            <p>
                {% if booking.status == 1 %}
                Booking Accepted
                {% else %}
                Booking Requested
                {% endif %}
            </p>
        </div>
    </div>

    <div class="row my-3">
        <div class="col-6">
            <h5>Booking Reference:</h5>
        </div>

        <div class="col-6">
            <p>{{ booking.booking_id}}</p>
        </div>
    </div>

    <div class="row my-3">
        <div class="col-6">
            <h5>Booking Date:</h5>
        </div>

        <div class="col-6">
            <p>{{ booking.booking_date }}</p>
        </div>
    </div>

    <div class="row my-3">
        <div class="col-6">
            <h5>Booking Time:</h5>
        </div>

        <div class="col-6">
            <p>{{ booking.booking_time }}</p>
        </div>
    </div>

<div class="container text-center mt-5">
    <div class="row my-3">
        <div class="col-12">
            {% if updated %}

            <div class="alert alert-success" role="alert">
                Your booking is awaiting approval
            </div>

            {% else %}

            {% if user.is_authenticated %}

            <form method="post">
                {% csrf_token %}

                {{ Update_BookingDetails | crispy }}

                <button type="submit" class="btn bg-success text-white my-3">Submit Changes</button>
            </form>

            {% endif %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}


{% if user.is_authenticated %}
<div class="container">
    <div class="custom-red py-3 my-5">
        <div class="row text-center">
            <h2 class="text-decoration-underline">Edit Profile</h2>
        </div>

        <div class="row text-center">
            <div class="col-6">
                <h4>First Name:</h4>
            </div>

            <div class="col-6">
                <p class="d-inline">{{ user.userprofile.first_name }}</p>
            </div>
        </div>

        <div class="row text-center">
            <div class="col-6">
                <h4>Last Name:</h4>
            </div>

            <div class="col-6">
                <p>{{ user.userprofile.last_name }}</p>
            </div>
        </div>

        <div class="row text-center">
            <div class="col-6">
                <h4>Dog Name:</h4>
            </div>

            <div class="col-6">
                <p>{{ user.userprofile.dog_name }}</p>
            </div>
        </div>

        <div class="row text-center">
            <div class="col-6">
                <h4>Telephone Number:</h4>
            </div>

            <div class="col-6">
                <p>{{ user.userprofile.phone_number}}</p>
            </div>
        </div>
    </div>

    <div class="row my-3">
        <div class="col-12">
            {% if updated %}
            <div class="alert alert-success" role="alert">
                You have successfully updated your profile.
            </div>

            {% else %}

            {% if user.is_authenticated %}

            <div class="w-75 mx-auto py-5">
                <form class="row g-3" method="post">
                    {% csrf_token %}

                    {{ Edit_ProfileForm | crispy }}

                    <div class="col-12 text-center">
                        <button type="submit" value="Update" class="btn bg-success text-white">
                            Update Profile
                        </button>
                    </div>
                </form>
            </div>
            {% endif %}

            {% endif %}

            {% else %}
            
            Please login to edit your profile

            {% endif %}

            {% endblock %}
        </div>
    </div>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-12 mt-3">
        <div class="w-75 mx-auto mt-2 text-center">
            <h1>
                Welcome to Pawfection Parlour
            </h1>

            <br>

            <h3>
               Only the best care for your best friend 
            <h3>
        </div>
    </div>
</div>
<br>
<div class="col-12 text-center">
    <a href="{% url 'online_booking' %}">
    <button type="submit" class="btn bg-success text-white">Book Now</button>
</a>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="row">
                <img class="w-75 mx-auto" id="banner"
                    src="https://res.cloudinary.com/dkxv7amyg/image/upload/v1652533153/Cover_Photo_fmjasj.jpg"
                    alt="homepage_banner">
            </div>
        </div>
        </div>
    </div>
</div>
<br>

{% endblock %}

templates/manage_booking.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center text-decoration-underline py-3">Manage my Bookings</h2>
        </div>
    </div>

    {% for booking in booking_list %}
    <div class="row py-5">
        <div class="col-12">
            <div class="card bg-dark">
                <div class="card-body ">
                    <h5 class="card-title">Booking Reference: {{ booking.booking_id }}</h5>
                    <p class="card-text">
                        Booking Status: {% if booking.status == 1 %}
                        Booking Accepted
                        {% else %}
                        Booking Requested
                        {% endif %}
                    </p>
                </div>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-dark text-white">Booking Date: {{ booking.booking_date }}</li>
                    <li class="list-group-item bg-dark text-white">Booking Time: {{ booking.booking_time }}</li>
                </ul>

                <div class="card-body d-flex">
                    <a href="{% url 'edit_booking' booking.booking_id %}" class="card-link btn bg-success text-white">
                        Change Booking Details
                    </a>
                    <a href="{% url 'delete_booking' booking.booking_id %}" class="card-link btn bg-success text-white">
                        Cancel Booking
                    </a>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock %}

templates/online_booking.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center text-decoration-underline py-3">Make a Booking</h2>
        </div>
    </div>

    {% if user.is_authenticated %}
    <div class="w-75 mx-auto py-5">
        <form class="row g-3" method="POST">
            {% csrf_token %}

            <div class="col-md-6 col-12">
                <label for="full_name">Full Name:</label>
                <input type="text" class="form-control" id="full_name" name="full_name"
                    value="{{ user.userprofile.first_name }} {{ user.userprofile.last_name }}" required>
            </div>

            <div class="col-md-6 col-12">
                <label for="phone_number">Contact Telephone Number:</label>
                <input type="number" class="form-control" id="phone_number" name="phone_number"
                    value="{{ user.userprofile.phone_number}}" minlength="11" maxlength="11" required>
            </div>

            <div class="col-md-6 col-12">
                <label for="date">Select a Date:</label>
                <input type="date" class="form-control" id="date" name="date" required>
            </div>

            <div class="col-md-6 col-12">
                <label for="time">Select a time:</label>
                <input type="time" class="form-control" id="time" name="time" min="14:00" max="23:00" value="14:00"
                    required>
            </div>

            <div class="col-12 text-center">
                <button type="submit" class="btn bg-success text-white">Book Now</button>
            </div>

        </form>

        <div class="container">
            <div class="row w-75 mx-auto">
                <div class="col-md-6 col-12">
                    <a class="nav-link text-white btn bg-success mx-auto mt-5 d-block"
                        href="{% url 'edit_profile' request.user.id %}">Edit Profile</a>
                </div>

                <div class="col-md-6 col-12">
                    <a class="nav-link text-white btn bg-success mx-auto mt-5 d-block"
                        href="{% url 'manage_booking' %}">My Bookings</a>
                </div>
            </div>
        </div>
    </div>

    {% else %}

    <div class="row my-3">
        <div class="col-12 text-center">
            If you are not logged in, please
            <a href="{% url 'account_signup' %}">signup</a>
            or
            <a href="{% url 'account_login' %}">login</a>
            first.
        </div>
    </div>

    {% endif %}
</div>

<script>
    Date.prototype.toDateInputValue = (function () {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    document.getElementById('date').value = new Date().toDateInputValue();
</script>

<script>
    var today = new Date().toISOString().split('T')[0];
    document.getElementsByName("date")[0].setAttribute('min', today);
</script>

{% endblock %}

templates/services.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <h1 class="text-center text-decoration-underline py-3 ">Services</h1>
  <div class="row">
    <div class="col-md-4 col-12 text-center">
      <h3 class="text-decoration-underline py-3">The Works</h3>
      <ul class="list-group">
        <li class="list-group-item">General Health Check</li>
        <li class="list-group-item">Eyes</li>
        <li class="list-group-item">Nail Clipping / Filing</li>
        <li class="list-group-item">Ear Cleaning / Plucking</li>
        <li class="list-group-item">Shaved Pads</li>
        <li class="list-group-item">Sani-Trim</li>
        <li class="list-group-item">Brushing, De-matting & de-shedding</li>
        <li class="list-group-item">Full Shampoo and Coat Conditioning</li>
        <li class="list-group-item">Anal Glands Expressed</li>
        <li class="list-group-item">Blowdried</li>
        <li class="list-group-item">Full Clipping, Scissoring, Trimming & Styling</li>

      </ul>
      <img src="https://res.cloudinary.com/dkxv7amyg/image/upload/v1652730217/IMG-20220516-WA0021_ecbwt0.jpg"
          alt="white_dog" style="width: 100%;" class="py-3">
    </div>

    <div class="col-md-4 col-12 text-center">
      <h2 class="text-decoration-underline py-3">Wash & Blowdry</h2>
      <ul class="list-group">
        <li class="list-group-item">Full Shampoo and Coat Conditioning</li>
        <li class="list-group-item">Blowdry</li>

      </ul>
      <img src="https://res.cloudinary.com/dkxv7amyg/image/upload/v1652730237/IMG-20220516-WA0014_hheybs.jpg"
          alt="washed_dog" style="width: 100%;" class="py-3">
    </div>

    <div class="col-md-4 col-12 text-center">
      <h2 class="text-decoration-underline py-3">Puppy Pamper</h2>
      <ul class="list-group">
        <li class="list-group-item">General Health Check</li>
        <li class="list-group-item">Eyes - Hair Tidy Up</li>
        <li class="list-group-item">Nail Clipping</li>
        <li class="list-group-item">Ear Cleaning</li>
        <li class="list-group-item">Bath, Brush and Blowdry</li>
        <li class="list-group-item"><p>This is a great introduction into grooming. All puppies should be fully vaccinated</p></li>
      </ul>
      <img src="https://res.cloudinary.com/dkxv7amyg/image/upload/v1652730216/IMG-20220516-WA0018_tbaxfy.jpg"
          alt="Puppy" style="width: 100%;" class="py-3">
    </div>
  </div>
</div>

{% endblock %}